name: hassfest

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
